#!/usr/bin/env bash
set -e

# ── Agent Skills Installer ─────────────────────────────────────────────────────
# Usage (recommended):
#   bash <(curl -fsSL https://raw.githubusercontent.com/OlixIgnacious/agent-skills/main/install.sh)
#
# Flags:
#   --global   Install into ~/.claude/ (available in every project) [default]
#   --local    Install into ./.claude/ (current project only)

REPO="https://raw.githubusercontent.com/OlixIgnacious/agent-skills/main"
BOLD="\033[1m"; CYAN="\033[36m"; GREEN="\033[32m"; YELLOW="\033[33m"; RESET="\033[0m"

header() { echo -e "\n${BOLD}${CYAN}$1${RESET}"; }
ok()     { echo -e "  ${GREEN}✓${RESET} $1"; }
info()   { echo -e "  ${YELLOW}→${RESET} $1"; }

header "Agent Skills Installer"
echo "  github.com/OlixIgnacious/agent-skills"

# ── Parse flags ────────────────────────────────────────────────────────────────
SCOPE="global"
for arg in "$@"; do
  case "$arg" in
    --local)  SCOPE="local" ;;
    --global) SCOPE="global" ;;
  esac
done

if [ "$SCOPE" = "global" ]; then
  CLAUDE_DEST="$HOME/.claude"
  echo -e "\nScope: ${BOLD}global${RESET} — available in every project"
  echo -e "Installing into: ${BOLD}$HOME/.claude${RESET}"
else
  CLAUDE_DEST="$(pwd)/.claude"
  echo -e "\nScope: ${BOLD}local${RESET} — this project only"
  echo -e "Installing into: ${BOLD}$(pwd)/.claude${RESET}"
fi

# Config files (CLAUDE.md, AGENTS.md, GEMINI.md) always go in current project dir
CONFIG_DEST="."

# ── Domain + tool selection ────────────────────────────────────────────────────
header "Select domain"
echo "  1) Kaggle   — competitive ML (12 skills, 3 agents)"
echo "  2) SDLC     — software development lifecycle (17 agents, 4 skills)"
echo "  3) Research — paper writing, literature search, venue selection (1 skill, 2 agents)"
echo "  4) All"
printf "  Choice [1/2/3/4]: "
read -r DOMAIN_CHOICE </dev/tty

case "$DOMAIN_CHOICE" in
  1) DOMAINS=("kaggle") ;;
  2) DOMAINS=("sdlc") ;;
  3) DOMAINS=("research") ;;
  4) DOMAINS=("kaggle" "sdlc" "research") ;;
  *) echo "  Invalid. Defaulting to All."; DOMAINS=("kaggle" "sdlc" "research") ;;
esac

header "Select tools"
echo "  1) Claude Code"
echo "  2) Antigravity (agy)"
echo "  3) GitHub Copilot"
echo "  4) All"
printf "  Choice [1/2/3/4]: "
read -r TOOL_CHOICE </dev/tty

case "$TOOL_CHOICE" in
  1) TOOLS=("claude") ;;
  2) TOOLS=("antigravity") ;;
  3) TOOLS=("copilot") ;;
  4) TOOLS=("claude" "antigravity" "copilot") ;;
  *) echo "  Invalid. Defaulting to All."; TOOLS=("claude" "antigravity" "copilot") ;;
esac

# ── Download helper ────────────────────────────────────────────────────────────
fetch() {
  local src="$1" dst="$2"
  mkdir -p "$(dirname "$dst")"
  if command -v curl &>/dev/null; then
    curl -fsSL "$src" -o "$dst"
  elif command -v wget &>/dev/null; then
    wget -q "$src" -O "$dst"
  else
    echo "Error: neither curl nor wget found." && exit 1
  fi
}

# ── Install Kaggle ─────────────────────────────────────────────────────────────
install_kaggle() {
  header "Installing Kaggle domain"

  local SKILLS=(
    kaggle-grandmaster kaggle-adversarial-validation kaggle-validation
    kaggle-eda kaggle-baselines kaggle-target-transform kaggle-optuna
    kaggle-feature-engineering kaggle-hill-climbing kaggle-stacking
    kaggle-pseudo-labeling kaggle-extra-training
  )

  local AGENTS=(
    kaggle-grandmaster kaggle-feature-engineer kaggle-ensemble-builder
  )

  for tool in "${TOOLS[@]}"; do
    case "$tool" in
      claude)
        for skill in "${SKILLS[@]}"; do
          fetch "$REPO/skills/$skill/SKILL.md" "$CLAUDE_DEST/skills/$skill/SKILL.md"
        done
        ok "${#SKILLS[@]} Kaggle skills → $CLAUDE_DEST/skills/"

        for agent in "${AGENTS[@]}"; do
          fetch "$REPO/agents/kaggle/$agent.md" "$CLAUDE_DEST/agents/$agent.md"
        done
        ok "${#AGENTS[@]} Kaggle agents → $CLAUDE_DEST/agents/"

        fetch "$REPO/domains/kaggle/ORCHESTRATION.md" "$CLAUDE_DEST/kaggle/ORCHESTRATION.md"
        ok "ORCHESTRATION.md → $CLAUDE_DEST/kaggle/"
        ;;
      antigravity)
        info "Kaggle skills are Claude Code format — AGENTS.md stub created for Antigravity"
        fetch "$REPO/domains/kaggle/ORCHESTRATION.md" "$CONFIG_DEST/KAGGLE_ORCHESTRATION.md"
        cat > "$CONFIG_DEST/AGENTS.md" <<'EOF'
# Kaggle Competition Workflow
<!-- Auto-generated by agent-skills installer -->
<!-- Full skills + agents available for Claude Code: github.com/OlixIgnacious/agent-skills -->

## Agents
- kaggle-grandmaster — competition orchestrator
- kaggle-feature-engineer — feature engineering specialist
- kaggle-ensemble-builder — ensemble and blending specialist

## Workflow
Phase 1: Adversarial validation → Fold strategy → EDA
Phase 2: Diverse baselines → Target transforms → Optuna → Feature engineering
Phase 3: Hill climbing → Stacking
Phase 4: Pseudo-labeling → Seed ensemble → Full-data retrain → Submit

See KAGGLE_ORCHESTRATION.md for the full phase-by-phase guide.
EOF
        ok "AGENTS.md + KAGGLE_ORCHESTRATION.md → $CONFIG_DEST/"
        ;;
      copilot)
        info "Kaggle domain has no Copilot config (skills are agentic, not inline suggestions)"
        ;;
    esac
  done
}

# ── Install SDLC ───────────────────────────────────────────────────────────────
install_sdlc() {
  header "Installing SDLC domain"

  local SDLC_SKILLS=(
    sdlc-biz-to-tech sdlc-architectural-review sdlc-feature-dev sdlc-code-review
  )

  local SDLC_AGENTS=(
    biz-to-tech-orchestrator architectural-review-orchestrator
    feature-dev-orchestrator code-review-orchestrator
    requirements-analyst code-archaeologist api-designer
    test-engineer technical-writer
    software-engineer database-internals devops-sre cybersecurity
    linux-debugging system-design competitive-programming ml-research
  )

  for tool in "${TOOLS[@]}"; do
    case "$tool" in
      claude)
        fetch "$REPO/domains/sdlc/CLAUDE.md" "$CONFIG_DEST/CLAUDE.md"
        fetch "$REPO/domains/sdlc/AGENTS.md"  "$CONFIG_DEST/AGENTS.md"
        ok "CLAUDE.md + AGENTS.md → $CONFIG_DEST/"

        for skill in "${SDLC_SKILLS[@]}"; do
          fetch "$REPO/skills/$skill/SKILL.md" "$CLAUDE_DEST/skills/$skill/SKILL.md"
        done
        ok "${#SDLC_SKILLS[@]} SDLC skills → $CLAUDE_DEST/skills/"

        for agent in "${SDLC_AGENTS[@]}"; do
          fetch "$REPO/agents/sdlc/$agent.md" "$CLAUDE_DEST/agents/$agent.md"
        done
        ok "${#SDLC_AGENTS[@]} SDLC agents → $CLAUDE_DEST/agents/"
        ;;
      antigravity)
        fetch "$REPO/domains/sdlc/AGENTS.md" "$CONFIG_DEST/AGENTS.md"
        fetch "$REPO/domains/sdlc/GEMINI.md" "$CONFIG_DEST/GEMINI.md"
        ok "AGENTS.md + GEMINI.md → $CONFIG_DEST/"
        ;;
      copilot)
        fetch "$REPO/domains/sdlc/copilot-instructions.md" \
              "$CONFIG_DEST/.github/copilot-instructions.md"
        ok ".github/copilot-instructions.md → $CONFIG_DEST/"
        ;;
    esac
  done
}

# ── Install Research ───────────────────────────────────────────────────────────
install_research() {
  header "Installing Research domain"

  local RESEARCH_AGENTS=(
    literature-reviewer venue-advisor
  )

  for tool in "${TOOLS[@]}"; do
    case "$tool" in
      claude)
        fetch "$REPO/skills/research-paper/SKILL.md" \
              "$CLAUDE_DEST/skills/research-paper/SKILL.md"
        ok "research-paper skill → $CLAUDE_DEST/skills/"

        for agent in "${RESEARCH_AGENTS[@]}"; do
          fetch "$REPO/agents/research/$agent.md" "$CLAUDE_DEST/agents/$agent.md"
        done
        ok "${#RESEARCH_AGENTS[@]} Research agents → $CLAUDE_DEST/agents/"

        fetch "$REPO/domains/research/AGENTS.md" "$CONFIG_DEST/AGENTS.md"
        ok "AGENTS.md → $CONFIG_DEST/"
        ;;
      antigravity)
        fetch "$REPO/domains/research/AGENTS.md" "$CONFIG_DEST/AGENTS.md"
        fetch "$REPO/domains/research/GEMINI.md" "$CONFIG_DEST/GEMINI.md"
        ok "AGENTS.md + GEMINI.md → $CONFIG_DEST/"
        ;;
      copilot)
        info "Research domain has no Copilot config (skill is agentic, not inline suggestions)"
        ;;
    esac
  done
}

# ── Install meta skill (always for Claude) ─────────────────────────────────────
install_meta() {
  local has_claude=0
  for t in "${TOOLS[@]}"; do [[ "$t" == "claude" ]] && has_claude=1; done
  if [ "$has_claude" -eq 1 ]; then
    fetch "$REPO/skills/skill-creator/SKILL.md" \
          "$CLAUDE_DEST/skills/skill-creator/SKILL.md"
    ok "skill-creator → $CLAUDE_DEST/skills/"
  fi
}

# ── Run installs ───────────────────────────────────────────────────────────────
for domain in "${DOMAINS[@]}"; do
  case "$domain" in
    kaggle)   install_kaggle ;;
    sdlc)     install_sdlc ;;
    research) install_research ;;
  esac
done

install_meta

# ── Post-install instructions ──────────────────────────────────────────────────
header "Done"

for domain in "${DOMAINS[@]}"; do
  case "$domain" in
    sdlc)
      echo -e "\n  ${BOLD}SDLC — next step:${RESET}"
      echo "  Edit the 'Codebase Context' section in CLAUDE.md / AGENTS.md"
      echo "  with your stack, conventions, and constraints."
      echo "  Then run: /sdlc-biz-to-tech"
      ;;
    kaggle)
      echo -e "\n  ${BOLD}Kaggle — next step:${RESET}"
      echo "  Start a Claude Code session and run: /kaggle-grandmaster"
      ;;
    research)
      echo -e "\n  ${BOLD}Research — next step:${RESET}"
      echo "  Start a Claude Code session and run: /research-paper"
      ;;
  esac
done

for tool in "${TOOLS[@]}"; do
  case "$tool" in
    claude)      echo -e "\n  Claude Code:  ${CYAN}claude${RESET} (in your project directory)" ;;
    antigravity) echo -e "\n  Antigravity:  ${CYAN}agy${RESET} (in your project directory)" ;;
    copilot)     echo -e "\n  Copilot:      Commit ${CYAN}.github/copilot-instructions.md${RESET} — auto-detected by VS Code" ;;
  esac
done

echo ""
