#!/usr/bin/env bash
set -e

# ── Agent Skills Installer ─────────────────────────────────────────────────────
# Usage: curl -fsSL https://raw.githubusercontent.com/OlixIgnacious/agent-skills/main/install.sh | bash
# Or:    bash install.sh  (from a local clone)

REPO="https://raw.githubusercontent.com/OlixIgnacious/agent-skills/main"
BOLD="\033[1m"; CYAN="\033[36m"; GREEN="\033[32m"; YELLOW="\033[33m"; RESET="\033[0m"

header() { echo -e "\n${BOLD}${CYAN}$1${RESET}"; }
ok()     { echo -e "  ${GREEN}✓${RESET} $1"; }
info()   { echo -e "  ${YELLOW}→${RESET} $1"; }

header "Agent Skills Installer"
echo "  github.com/OlixIgnacious/agent-skills"

# ── Detect destination ─────────────────────────────────────────────────────────
DEST="${1:-.}"
if [ "$DEST" = "." ]; then
  echo -e "\nInstalling into current directory: ${BOLD}$(pwd)${RESET}"
else
  echo -e "\nInstalling into: ${BOLD}$DEST${RESET}"
  mkdir -p "$DEST"
fi

# ── Domain selection ───────────────────────────────────────────────────────────
header "Select domain"
echo "  1) Kaggle  — competitive ML (12 skills, 3 agents)"
echo "  2) SDLC    — software development lifecycle (17 agents, 4 skills)"
echo "  3) Both"
echo -n "  Choice [1/2/3]: "
read -r DOMAIN_CHOICE

case "$DOMAIN_CHOICE" in
  1) DOMAINS=("kaggle") ;;
  2) DOMAINS=("sdlc") ;;
  3) DOMAINS=("kaggle" "sdlc") ;;
  *) echo "Invalid choice. Defaulting to both."; DOMAINS=("kaggle" "sdlc") ;;
esac

# ── Tool selection ─────────────────────────────────────────────────────────────
header "Select tools"
echo "  1) Claude Code"
echo "  2) Antigravity (agy)"
echo "  3) GitHub Copilot"
echo "  4) All"
echo -n "  Choice [1/2/3/4]: "
read -r TOOL_CHOICE

case "$TOOL_CHOICE" in
  1) TOOLS=("claude") ;;
  2) TOOLS=("antigravity") ;;
  3) TOOLS=("copilot") ;;
  4) TOOLS=("claude" "antigravity" "copilot") ;;
  *) echo "Invalid choice. Defaulting to all."; TOOLS=("claude" "antigravity" "copilot") ;;
esac

# ── Download helper ────────────────────────────────────────────────────────────
fetch() {
  local src="$1" dst="$2"
  mkdir -p "$(dirname "$dst")"
  if command -v curl &>/dev/null; then
    curl -fsSL "$src" -o "$dst"
  elif command -v wget &>/dev/null; then
    wget -q "$src" -O "$dst"
  else
    echo "Error: neither curl nor wget found." && exit 1
  fi
}

# ── Install SDLC files ─────────────────────────────────────────────────────────
install_sdlc() {
  header "Installing SDLC domain"

  for tool in "${TOOLS[@]}"; do
    case "$tool" in
      claude)
        fetch "$REPO/domains/sdlc/CLAUDE.md" "$DEST/CLAUDE.md"
        fetch "$REPO/domains/sdlc/AGENTS.md"  "$DEST/AGENTS.md"
        ok "CLAUDE.md + AGENTS.md → $DEST/"
        ;;
      antigravity)
        fetch "$REPO/domains/sdlc/AGENTS.md"  "$DEST/AGENTS.md"
        fetch "$REPO/domains/sdlc/GEMINI.md"  "$DEST/GEMINI.md"
        ok "AGENTS.md + GEMINI.md → $DEST/"
        ;;
      copilot)
        fetch "$REPO/domains/sdlc/copilot-instructions.md" \
              "$DEST/.github/copilot-instructions.md"
        ok ".github/copilot-instructions.md → $DEST/"
        ;;
    esac
  done
}

# ── Install Kaggle files ───────────────────────────────────────────────────────
install_kaggle() {
  header "Installing Kaggle domain"

  # Skills always go into .claude/skills/ for Claude Code local use
  SKILLS=(
    kaggle-grandmaster kaggle-adversarial-validation kaggle-validation
    kaggle-eda kaggle-baselines kaggle-target-transform kaggle-optuna
    kaggle-feature-engineering kaggle-hill-climbing kaggle-stacking
    kaggle-pseudo-labeling kaggle-extra-training
  )

  for tool in "${TOOLS[@]}"; do
    case "$tool" in
      claude)
        for skill in "${SKILLS[@]}"; do
          fetch "$REPO/skills/$skill/SKILL.md" \
                "$DEST/.claude/skills/$skill/SKILL.md"
        done
        ok "${#SKILLS[@]} Kaggle skills → $DEST/.claude/skills/"

        fetch "$REPO/domains/kaggle/ORCHESTRATION.md" \
              "$DEST/.claude/kaggle/ORCHESTRATION.md"
        ok "ORCHESTRATION.md → $DEST/.claude/kaggle/"
        ;;
      antigravity)
        info "Kaggle skills are Claude Code format — AGENTS.md stub created for Antigravity"
        fetch "$REPO/domains/kaggle/ORCHESTRATION.md" "$DEST/KAGGLE_ORCHESTRATION.md"
        cat > "$DEST/AGENTS.md" <<'EOF'
# Kaggle Competition Workflow
<!-- Auto-generated by agent-skills installer -->
<!-- Full skills available for Claude Code: /plugin install OlixIgnacious/agent-skills -->

## Workflow
Phase 1: Adversarial validation → Fold strategy → EDA
Phase 2: Diverse baselines → Target transforms → Optuna → Feature engineering
Phase 3: Hill climbing → Stacking
Phase 4: Pseudo-labeling → Seed ensemble → Full-data retrain → Submit

See KAGGLE_ORCHESTRATION.md for the full phase-by-phase guide.
EOF
        ok "AGENTS.md + KAGGLE_ORCHESTRATION.md → $DEST/"
        ;;
      copilot)
        info "Kaggle domain has no Copilot config (skills are agentic, not inline suggestions)"
        ;;
    esac
  done
}

# ── Run installs ───────────────────────────────────────────────────────────────
for domain in "${DOMAINS[@]}"; do
  case "$domain" in
    sdlc)   install_sdlc ;;
    kaggle) install_kaggle ;;
  esac
done

# ── Post-install instructions ──────────────────────────────────────────────────
header "Done"

for domain in "${DOMAINS[@]}"; do
  if [ "$domain" = "sdlc" ]; then
    echo ""
    echo -e "  ${BOLD}SDLC — next step:${RESET}"
    echo "  Edit the 'Codebase Context' section in the installed files"
    echo "  with your stack, conventions, and constraints."
  fi
  if [ "$domain" = "kaggle" ]; then
    echo ""
    echo -e "  ${BOLD}Kaggle — next step:${RESET}"
    echo "  Start a Claude Code session and run: /kaggle-grandmaster"
  fi
done

for tool in "${TOOLS[@]}"; do
  case "$tool" in
    claude)      echo -e "\n  Claude Code:  ${CYAN}claude${RESET} (in your project directory)" ;;
    antigravity) echo -e "\n  Antigravity:  ${CYAN}agy${RESET} (in your project directory)" ;;
    copilot)     echo -e "\n  Copilot:      Commit ${CYAN}.github/copilot-instructions.md${RESET} — auto-detected by VS Code" ;;
  esac
done

echo ""
